// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// AddRSVP provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) AddRSVP(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddRSVP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_AddRSVP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRSVP'
type MockEventRepository_AddRSVP_Call struct {
	*mock.Call
}

// AddRSVP is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - userID uuid.UUID
func (_e *MockEventRepository_Expecter) AddRSVP(ctx any, eventID any, userID any) *MockEventRepository_AddRSVP_Call {
	return &MockEventRepository_AddRSVP_Call{Call: _e.mock.On("AddRSVP", ctx, eventID, userID)}
}

func (_c *MockEventRepository_AddRSVP_Call) Run(run func(ctx context.Context, eventID uuid.UUID, userID uuid.UUID)) *MockEventRepository_AddRSVP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_AddRSVP_Call) Return(err error) *MockEventRepository_AddRSVP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_AddRSVP_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) error) *MockEventRepository_AddRSVP_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Cancel(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockEventRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEventRepository_Expecter) Cancel(ctx any, id any) *MockEventRepository_Cancel_Call {
	return &MockEventRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockEventRepository_Cancel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEventRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Cancel_Call) Return(err error) *MockEventRepository_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockEventRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Create(ctx context.Context, e *Event) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Event) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *Event
func (_e *MockEventRepository_Expecter) Create(ctx any, e any) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(ctx context.Context, e *Event)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Event
		if args[1] != nil {
			arg1 = args[1].(*Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(err error) *MockEventRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, e *Event) error) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEventRepository_Expecter) Delete(ctx any, id any) *MockEventRepository_Delete_Call {
	return &MockEventRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEventRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Delete_Call) Return(err error) *MockEventRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockEventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) GetByID(ctx context.Context, id uuid.UUID) (*Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEventRepository_Expecter) GetByID(ctx any, id any) *MockEventRepository_GetByID_Call {
	return &MockEventRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockEventRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_GetByID_Call) Return(event *Event, err error) *MockEventRepository_GetByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Event, error)) *MockEventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) List(ctx context.Context, includeCanceled bool) ([]Event, error) {
	ret := _mock.Called(ctx, includeCanceled)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]Event, error)); ok {
		return returnFunc(ctx, includeCanceled)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []Event); ok {
		r0 = returnFunc(ctx, includeCanceled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeCanceled)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - includeCanceled bool
func (_e *MockEventRepository_Expecter) List(ctx any, includeCanceled any) *MockEventRepository_List_Call {
	return &MockEventRepository_List_Call{Call: _e.mock.On("List", ctx, includeCanceled)}
}

func (_c *MockEventRepository_List_Call) Run(run func(ctx context.Context, includeCanceled bool)) *MockEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_List_Call) Return(events []Event, err error) *MockEventRepository_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_List_Call) RunAndReturn(run func(ctx context.Context, includeCanceled bool) ([]Event, error)) *MockEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RSVPAvatars provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) RSVPAvatars(ctx context.Context, eventIDs []uuid.UUID, limit int) (map[uuid.UUID][]string, error) {
	ret := _mock.Called(ctx, eventIDs, limit)

	if len(ret) == 0 {
		panic("no return value specified for RSVPAvatars")
	}

	var r0 map[uuid.UUID][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, int) (map[uuid.UUID][]string, error)); ok {
		return returnFunc(ctx, eventIDs, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, int) map[uuid.UUID][]string); ok {
		r0 = returnFunc(ctx, eventIDs, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, eventIDs, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_RSVPAvatars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RSVPAvatars'
type MockEventRepository_RSVPAvatars_Call struct {
	*mock.Call
}

// RSVPAvatars is a helper method to define mock.On call
//   - ctx context.Context
//   - eventIDs []uuid.UUID
//   - limit int
func (_e *MockEventRepository_Expecter) RSVPAvatars(ctx any, eventIDs any, limit any) *MockEventRepository_RSVPAvatars_Call {
	return &MockEventRepository_RSVPAvatars_Call{Call: _e.mock.On("RSVPAvatars", ctx, eventIDs, limit)}
}

func (_c *MockEventRepository_RSVPAvatars_Call) Run(run func(ctx context.Context, eventIDs []uuid.UUID, limit int)) *MockEventRepository_RSVPAvatars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_RSVPAvatars_Call) Return(uUIDToStrings map[uuid.UUID][]string, err error) *MockEventRepository_RSVPAvatars_Call {
	_c.Call.Return(uUIDToStrings, err)
	return _c
}

func (_c *MockEventRepository_RSVPAvatars_Call) RunAndReturn(run func(ctx context.Context, eventIDs []uuid.UUID, limit int) (map[uuid.UUID][]string, error)) *MockEventRepository_RSVPAvatars_Call {
	_c.Call.Return(run)
	return _c
}

// RSVPCounts provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) RSVPCounts(ctx context.Context, eventIDs []uuid.UUID) (map[uuid.UUID]int, error) {
	ret := _mock.Called(ctx, eventIDs)

	if len(ret) == 0 {
		panic("no return value specified for RSVPCounts")
	}

	var r0 map[uuid.UUID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]int, error)); ok {
		return returnFunc(ctx, eventIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]int); ok {
		r0 = returnFunc(ctx, eventIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, eventIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_RSVPCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RSVPCounts'
type MockEventRepository_RSVPCounts_Call struct {
	*mock.Call
}

// RSVPCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - eventIDs []uuid.UUID
func (_e *MockEventRepository_Expecter) RSVPCounts(ctx any, eventIDs any) *MockEventRepository_RSVPCounts_Call {
	return &MockEventRepository_RSVPCounts_Call{Call: _e.mock.On("RSVPCounts", ctx, eventIDs)}
}

func (_c *MockEventRepository_RSVPCounts_Call) Run(run func(ctx context.Context, eventIDs []uuid.UUID)) *MockEventRepository_RSVPCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_RSVPCounts_Call) Return(uUIDToInt map[uuid.UUID]int, err error) *MockEventRepository_RSVPCounts_Call {
	_c.Call.Return(uUIDToInt, err)
	return _c
}

func (_c *MockEventRepository_RSVPCounts_Call) RunAndReturn(run func(ctx context.Context, eventIDs []uuid.UUID) (map[uuid.UUID]int, error)) *MockEventRepository_RSVPCounts_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRSVP provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) RemoveRSVP(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRSVP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_RemoveRSVP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRSVP'
type MockEventRepository_RemoveRSVP_Call struct {
	*mock.Call
}

// RemoveRSVP is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - userID uuid.UUID
func (_e *MockEventRepository_Expecter) RemoveRSVP(ctx any, eventID any, userID any) *MockEventRepository_RemoveRSVP_Call {
	return &MockEventRepository_RemoveRSVP_Call{Call: _e.mock.On("RemoveRSVP", ctx, eventID, userID)}
}

func (_c *MockEventRepository_RemoveRSVP_Call) Run(run func(ctx context.Context, eventID uuid.UUID, userID uuid.UUID)) *MockEventRepository_RemoveRSVP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_RemoveRSVP_Call) Return(err error) *MockEventRepository_RemoveRSVP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_RemoveRSVP_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) error) *MockEventRepository_RemoveRSVP_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Update(ctx context.Context, e *Event) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Event) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - e *Event
func (_e *MockEventRepository_Expecter) Update(ctx any, e any) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, e)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(ctx context.Context, e *Event)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Event
		if args[1] != nil {
			arg1 = args[1].(*Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(err error) *MockEventRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(ctx context.Context, e *Event) error) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// ViewerRSVPed provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ViewerRSVPed(ctx context.Context, eventIDs []uuid.UUID, userID uuid.UUID) (map[uuid.UUID]bool, error) {
	ret := _mock.Called(ctx, eventIDs, userID)

	if len(ret) == 0 {
		panic("no return value specified for ViewerRSVPed")
	}

	var r0 map[uuid.UUID]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, uuid.UUID) (map[uuid.UUID]bool, error)); ok {
		return returnFunc(ctx, eventIDs, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, uuid.UUID) map[uuid.UUID]bool); ok {
		r0 = returnFunc(ctx, eventIDs, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, eventIDs, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_ViewerRSVPed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewerRSVPed'
type MockEventRepository_ViewerRSVPed_Call struct {
	*mock.Call
}

// ViewerRSVPed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventIDs []uuid.UUID
//   - userID uuid.UUID
func (_e *MockEventRepository_Expecter) ViewerRSVPed(ctx any, eventIDs any, userID any) *MockEventRepository_ViewerRSVPed_Call {
	return &MockEventRepository_ViewerRSVPed_Call{Call: _e.mock.On("ViewerRSVPed", ctx, eventIDs, userID)}
}

func (_c *MockEventRepository_ViewerRSVPed_Call) Run(run func(ctx context.Context, eventIDs []uuid.UUID, userID uuid.UUID)) *MockEventRepository_ViewerRSVPed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ViewerRSVPed_Call) Return(uUIDToBool map[uuid.UUID]bool, err error) *MockEventRepository_ViewerRSVPed_Call {
	_c.Call.Return(uUIDToBool, err)
	return _c
}

func (_c *MockEventRepository_ViewerRSVPed_Call) RunAndReturn(run func(ctx context.Context, eventIDs []uuid.UUID, userID uuid.UUID) (map[uuid.UUID]bool, error)) *MockEventRepository_ViewerRSVPed_Call {
	_c.Call.Return(run)
	return _c
}
