// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMapRepository creates a new instance of MockMapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapRepository {
	mock := &MockMapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMapRepository is an autogenerated mock type for the MapRepository type
type MockMapRepository struct {
	mock.Mock
}

type MockMapRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMapRepository) EXPECT() *MockMapRepository_Expecter {
	return &MockMapRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Create(ctx context.Context, m *Map) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Map) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMapRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMapRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *Map
func (_e *MockMapRepository_Expecter) Create(ctx any, m any) *MockMapRepository_Create_Call {
	return &MockMapRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockMapRepository_Create_Call) Run(run func(ctx context.Context, m *Map)) *MockMapRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Map
		if args[1] != nil {
			arg1 = args[1].(*Map)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_Create_Call) Return(err error) *MockMapRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMapRepository_Create_Call) RunAndReturn(run func(ctx context.Context, m *Map) error) *MockMapRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMapRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMapRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMapRepository_Expecter) Delete(ctx any, id any) *MockMapRepository_Delete_Call {
	return &MockMapRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMapRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMapRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_Delete_Call) Return(err error) *MockMapRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMapRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockMapRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Get(ctx context.Context, id uuid.UUID) (*Map, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Map
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Map, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Map); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Map)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMapRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMapRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMapRepository_Expecter) Get(ctx any, id any) *MockMapRepository_Get_Call {
	return &MockMapRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMapRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMapRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_Get_Call) Return(mapParam *Map, err error) *MockMapRepository_Get_Call {
	_c.Call.Return(mapParam, err)
	return _c
}

func (_c *MockMapRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Map, error)) *MockMapRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) List(ctx context.Context) ([]Map, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Map
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Map, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Map); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Map)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMapRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMapRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMapRepository_Expecter) List(ctx any) *MockMapRepository_List_Call {
	return &MockMapRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMapRepository_List_Call) Run(run func(ctx context.Context)) *MockMapRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapRepository_List_Call) Return(maps []Map, err error) *MockMapRepository_List_Call {
	_c.Call.Return(maps, err)
	return _c
}

func (_c *MockMapRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]Map, error)) *MockMapRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Update(ctx context.Context, m *Map) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Map) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMapRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMapRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - m *Map
func (_e *MockMapRepository_Expecter) Update(ctx any, m any) *MockMapRepository_Update_Call {
	return &MockMapRepository_Update_Call{Call: _e.mock.On("Update", ctx, m)}
}

func (_c *MockMapRepository_Update_Call) Run(run func(ctx context.Context, m *Map)) *MockMapRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Map
		if args[1] != nil {
			arg1 = args[1].(*Map)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_Update_Call) Return(err error) *MockMapRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMapRepository_Update_Call) RunAndReturn(run func(ctx context.Context, m *Map) error) *MockMapRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
