// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVaultRepository creates a new instance of MockVaultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultRepository {
	mock := &MockVaultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVaultRepository is an autogenerated mock type for the VaultRepository type
type MockVaultRepository struct {
	mock.Mock
}

type MockVaultRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultRepository) EXPECT() *MockVaultRepository_Expecter {
	return &MockVaultRepository_Expecter{mock: &_m.Mock}
}

// ChainLocked provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) ChainLocked(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ChainLocked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_ChainLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainLocked'
type MockVaultRepository_ChainLocked_Call struct {
	*mock.Call
}

// ChainLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) ChainLocked(ctx any, id any) *MockVaultRepository_ChainLocked_Call {
	return &MockVaultRepository_ChainLocked_Call{Call: _e.mock.On("ChainLocked", ctx, id)}
}

func (_c *MockVaultRepository_ChainLocked_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_ChainLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_ChainLocked_Call) Return(b bool, err error) *MockVaultRepository_ChainLocked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockVaultRepository_ChainLocked_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockVaultRepository_ChainLocked_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) CreateFile(ctx context.Context, f *VaultFile) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VaultFile) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockVaultRepository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - f *VaultFile
func (_e *MockVaultRepository_Expecter) CreateFile(ctx any, f any) *MockVaultRepository_CreateFile_Call {
	return &MockVaultRepository_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, f)}
}

func (_c *MockVaultRepository_CreateFile_Call) Run(run func(ctx context.Context, f *VaultFile)) *MockVaultRepository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *VaultFile
		if args[1] != nil {
			arg1 = args[1].(*VaultFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_CreateFile_Call) Return(err error) *MockVaultRepository_CreateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_CreateFile_Call) RunAndReturn(run func(ctx context.Context, f *VaultFile) error) *MockVaultRepository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFolder provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) CreateFolder(ctx context.Context, f *VaultFolder) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for CreateFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *VaultFolder) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_CreateFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFolder'
type MockVaultRepository_CreateFolder_Call struct {
	*mock.Call
}

// CreateFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - f *VaultFolder
func (_e *MockVaultRepository_Expecter) CreateFolder(ctx any, f any) *MockVaultRepository_CreateFolder_Call {
	return &MockVaultRepository_CreateFolder_Call{Call: _e.mock.On("CreateFolder", ctx, f)}
}

func (_c *MockVaultRepository_CreateFolder_Call) Run(run func(ctx context.Context, f *VaultFolder)) *MockVaultRepository_CreateFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *VaultFolder
		if args[1] != nil {
			arg1 = args[1].(*VaultFolder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_CreateFolder_Call) Return(err error) *MockVaultRepository_CreateFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_CreateFolder_Call) RunAndReturn(run func(ctx context.Context, f *VaultFolder) error) *MockVaultRepository_CreateFolder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) DeleteFile(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockVaultRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) DeleteFile(ctx any, id any) *MockVaultRepository_DeleteFile_Call {
	return &MockVaultRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *MockVaultRepository_DeleteFile_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_DeleteFile_Call) Return(err error) *MockVaultRepository_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockVaultRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFolder provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type MockVaultRepository_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) DeleteFolder(ctx any, id any) *MockVaultRepository_DeleteFolder_Call {
	return &MockVaultRepository_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, id)}
}

func (_c *MockVaultRepository_DeleteFolder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_DeleteFolder_Call) Return(err error) *MockVaultRepository_DeleteFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_DeleteFolder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockVaultRepository_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// DescendantStoredNames provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) DescendantStoredNames(ctx context.Context, id uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DescendantStoredNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_DescendantStoredNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescendantStoredNames'
type MockVaultRepository_DescendantStoredNames_Call struct {
	*mock.Call
}

// DescendantStoredNames is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) DescendantStoredNames(ctx any, id any) *MockVaultRepository_DescendantStoredNames_Call {
	return &MockVaultRepository_DescendantStoredNames_Call{Call: _e.mock.On("DescendantStoredNames", ctx, id)}
}

func (_c *MockVaultRepository_DescendantStoredNames_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_DescendantStoredNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_DescendantStoredNames_Call) Return(strings []string, err error) *MockVaultRepository_DescendantStoredNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockVaultRepository_DescendantStoredNames_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) ([]string, error)) *MockVaultRepository_DescendantStoredNames_Call {
	_c.Call.Return(run)
	return _c
}

// FolderChain provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) FolderChain(ctx context.Context, id uuid.UUID) ([]VaultFolder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FolderChain")
	}

	var r0 []VaultFolder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]VaultFolder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []VaultFolder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VaultFolder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_FolderChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FolderChain'
type MockVaultRepository_FolderChain_Call struct {
	*mock.Call
}

// FolderChain is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) FolderChain(ctx any, id any) *MockVaultRepository_FolderChain_Call {
	return &MockVaultRepository_FolderChain_Call{Call: _e.mock.On("FolderChain", ctx, id)}
}

func (_c *MockVaultRepository_FolderChain_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_FolderChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_FolderChain_Call) Return(vaultFolders []VaultFolder, err error) *MockVaultRepository_FolderChain_Call {
	_c.Call.Return(vaultFolders, err)
	return _c
}

func (_c *MockVaultRepository_FolderChain_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) ([]VaultFolder, error)) *MockVaultRepository_FolderChain_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) GetFile(ctx context.Context, id uuid.UUID) (*VaultFile, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *VaultFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*VaultFile, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *VaultFile); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VaultFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockVaultRepository_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) GetFile(ctx any, id any) *MockVaultRepository_GetFile_Call {
	return &MockVaultRepository_GetFile_Call{Call: _e.mock.On("GetFile", ctx, id)}
}

func (_c *MockVaultRepository_GetFile_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_GetFile_Call) Return(vaultFile *VaultFile, err error) *MockVaultRepository_GetFile_Call {
	_c.Call.Return(vaultFile, err)
	return _c
}

func (_c *MockVaultRepository_GetFile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*VaultFile, error)) *MockVaultRepository_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolder provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) GetFolder(ctx context.Context, id uuid.UUID) (*VaultFolder, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFolder")
	}

	var r0 *VaultFolder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*VaultFolder, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *VaultFolder); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VaultFolder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_GetFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolder'
type MockVaultRepository_GetFolder_Call struct {
	*mock.Call
}

// GetFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVaultRepository_Expecter) GetFolder(ctx any, id any) *MockVaultRepository_GetFolder_Call {
	return &MockVaultRepository_GetFolder_Call{Call: _e.mock.On("GetFolder", ctx, id)}
}

func (_c *MockVaultRepository_GetFolder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVaultRepository_GetFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVaultRepository_GetFolder_Call) Return(vaultFolder *VaultFolder, err error) *MockVaultRepository_GetFolder_Call {
	_c.Call.Return(vaultFolder, err)
	return _c
}

func (_c *MockVaultRepository_GetFolder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*VaultFolder, error)) *MockVaultRepository_GetFolder_Call {
	_c.Call.Return(run)
	return _c
}

// ListChildFolders provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) ListChildFolders(ctx context.Context, parentID *uuid.UUID, includeLocked bool) ([]VaultFolder, error) {
	ret := _mock.Called(ctx, parentID, includeLocked)

	if len(ret) == 0 {
		panic("no return value specified for ListChildFolders")
	}

	var r0 []VaultFolder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, bool) ([]VaultFolder, error)); ok {
		return returnFunc(ctx, parentID, includeLocked)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, bool) []VaultFolder); ok {
		r0 = returnFunc(ctx, parentID, includeLocked)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VaultFolder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, parentID, includeLocked)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_ListChildFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChildFolders'
type MockVaultRepository_ListChildFolders_Call struct {
	*mock.Call
}

// ListChildFolders is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *uuid.UUID
//   - includeLocked bool
func (_e *MockVaultRepository_Expecter) ListChildFolders(ctx any, parentID any, includeLocked any) *MockVaultRepository_ListChildFolders_Call {
	return &MockVaultRepository_ListChildFolders_Call{Call: _e.mock.On("ListChildFolders", ctx, parentID, includeLocked)}
}

func (_c *MockVaultRepository_ListChildFolders_Call) Run(run func(ctx context.Context, parentID *uuid.UUID, includeLocked bool)) *MockVaultRepository_ListChildFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_ListChildFolders_Call) Return(vaultFolders []VaultFolder, err error) *MockVaultRepository_ListChildFolders_Call {
	_c.Call.Return(vaultFolders, err)
	return _c
}

func (_c *MockVaultRepository_ListChildFolders_Call) RunAndReturn(run func(ctx context.Context, parentID *uuid.UUID, includeLocked bool) ([]VaultFolder, error)) *MockVaultRepository_ListChildFolders_Call {
	_c.Call.Return(run)
	return _c
}

// ListFolderFiles provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) ListFolderFiles(ctx context.Context, folderID *uuid.UUID, includeLocked bool) ([]VaultFile, error) {
	ret := _mock.Called(ctx, folderID, includeLocked)

	if len(ret) == 0 {
		panic("no return value specified for ListFolderFiles")
	}

	var r0 []VaultFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, bool) ([]VaultFile, error)); ok {
		return returnFunc(ctx, folderID, includeLocked)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, bool) []VaultFile); ok {
		r0 = returnFunc(ctx, folderID, includeLocked)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]VaultFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, folderID, includeLocked)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepository_ListFolderFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFolderFiles'
type MockVaultRepository_ListFolderFiles_Call struct {
	*mock.Call
}

// ListFolderFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID *uuid.UUID
//   - includeLocked bool
func (_e *MockVaultRepository_Expecter) ListFolderFiles(ctx any, folderID any, includeLocked any) *MockVaultRepository_ListFolderFiles_Call {
	return &MockVaultRepository_ListFolderFiles_Call{Call: _e.mock.On("ListFolderFiles", ctx, folderID, includeLocked)}
}

func (_c *MockVaultRepository_ListFolderFiles_Call) Run(run func(ctx context.Context, folderID *uuid.UUID, includeLocked bool)) *MockVaultRepository_ListFolderFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_ListFolderFiles_Call) Return(vaultFiles []VaultFile, err error) *MockVaultRepository_ListFolderFiles_Call {
	_c.Call.Return(vaultFiles, err)
	return _c
}

func (_c *MockVaultRepository_ListFolderFiles_Call) RunAndReturn(run func(ctx context.Context, folderID *uuid.UUID, includeLocked bool) ([]VaultFile, error)) *MockVaultRepository_ListFolderFiles_Call {
	_c.Call.Return(run)
	return _c
}

// RenameFile provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) RenameFile(ctx context.Context, id uuid.UUID, name string) error {
	ret := _mock.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_RenameFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameFile'
type MockVaultRepository_RenameFile_Call struct {
	*mock.Call
}

// RenameFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *MockVaultRepository_Expecter) RenameFile(ctx any, id any, name any) *MockVaultRepository_RenameFile_Call {
	return &MockVaultRepository_RenameFile_Call{Call: _e.mock.On("RenameFile", ctx, id, name)}
}

func (_c *MockVaultRepository_RenameFile_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *MockVaultRepository_RenameFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_RenameFile_Call) Return(err error) *MockVaultRepository_RenameFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_RenameFile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, name string) error) *MockVaultRepository_RenameFile_Call {
	_c.Call.Return(run)
	return _c
}

// RenameFolder provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) RenameFolder(ctx context.Context, id uuid.UUID, name string) error {
	ret := _mock.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_RenameFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameFolder'
type MockVaultRepository_RenameFolder_Call struct {
	*mock.Call
}

// RenameFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *MockVaultRepository_Expecter) RenameFolder(ctx any, id any, name any) *MockVaultRepository_RenameFolder_Call {
	return &MockVaultRepository_RenameFolder_Call{Call: _e.mock.On("RenameFolder", ctx, id, name)}
}

func (_c *MockVaultRepository_RenameFolder_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *MockVaultRepository_RenameFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_RenameFolder_Call) Return(err error) *MockVaultRepository_RenameFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_RenameFolder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, name string) error) *MockVaultRepository_RenameFolder_Call {
	_c.Call.Return(run)
	return _c
}

// SetFileLocked provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) SetFileLocked(ctx context.Context, id uuid.UUID, locked bool) error {
	ret := _mock.Called(ctx, id, locked)

	if len(ret) == 0 {
		panic("no return value specified for SetFileLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, locked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_SetFileLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFileLocked'
type MockVaultRepository_SetFileLocked_Call struct {
	*mock.Call
}

// SetFileLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - locked bool
func (_e *MockVaultRepository_Expecter) SetFileLocked(ctx any, id any, locked any) *MockVaultRepository_SetFileLocked_Call {
	return &MockVaultRepository_SetFileLocked_Call{Call: _e.mock.On("SetFileLocked", ctx, id, locked)}
}

func (_c *MockVaultRepository_SetFileLocked_Call) Run(run func(ctx context.Context, id uuid.UUID, locked bool)) *MockVaultRepository_SetFileLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_SetFileLocked_Call) Return(err error) *MockVaultRepository_SetFileLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_SetFileLocked_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, locked bool) error) *MockVaultRepository_SetFileLocked_Call {
	_c.Call.Return(run)
	return _c
}

// SetFolderLocked provides a mock function for the type MockVaultRepository
func (_mock *MockVaultRepository) SetFolderLocked(ctx context.Context, id uuid.UUID, locked bool) error {
	ret := _mock.Called(ctx, id, locked)

	if len(ret) == 0 {
		panic("no return value specified for SetFolderLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, locked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepository_SetFolderLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFolderLocked'
type MockVaultRepository_SetFolderLocked_Call struct {
	*mock.Call
}

// SetFolderLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - locked bool
func (_e *MockVaultRepository_Expecter) SetFolderLocked(ctx any, id any, locked any) *MockVaultRepository_SetFolderLocked_Call {
	return &MockVaultRepository_SetFolderLocked_Call{Call: _e.mock.On("SetFolderLocked", ctx, id, locked)}
}

func (_c *MockVaultRepository_SetFolderLocked_Call) Run(run func(ctx context.Context, id uuid.UUID, locked bool)) *MockVaultRepository_SetFolderLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVaultRepository_SetFolderLocked_Call) Return(err error) *MockVaultRepository_SetFolderLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepository_SetFolderLocked_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, locked bool) error) *MockVaultRepository_SetFolderLocked_Call {
	_c.Call.Return(run)
	return _c
}
