// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherRepository creates a new instance of MockWeatherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherRepository {
	mock := &MockWeatherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherRepository is an autogenerated mock type for the WeatherRepository type
type MockWeatherRepository struct {
	mock.Mock
}

type MockWeatherRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherRepository) EXPECT() *MockWeatherRepository_Expecter {
	return &MockWeatherRepository_Expecter{mock: &_m.Mock}
}

// CountForUser provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) CountForUser(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountForUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherRepository_CountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountForUser'
type MockWeatherRepository_CountForUser_Call struct {
	*mock.Call
}

// CountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWeatherRepository_Expecter) CountForUser(ctx any, userID any) *MockWeatherRepository_CountForUser_Call {
	return &MockWeatherRepository_CountForUser_Call{Call: _e.mock.On("CountForUser", ctx, userID)}
}

func (_c *MockWeatherRepository_CountForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWeatherRepository_CountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_CountForUser_Call) Return(n int, err error) *MockWeatherRepository_CountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWeatherRepository_CountForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockWeatherRepository_CountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) Create(ctx context.Context, l *WeatherLocation) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *WeatherLocation) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeatherRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWeatherRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - l *WeatherLocation
func (_e *MockWeatherRepository_Expecter) Create(ctx any, l any) *MockWeatherRepository_Create_Call {
	return &MockWeatherRepository_Create_Call{Call: _e.mock.On("Create", ctx, l)}
}

func (_c *MockWeatherRepository_Create_Call) Run(run func(ctx context.Context, l *WeatherLocation)) *MockWeatherRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *WeatherLocation
		if args[1] != nil {
			arg1 = args[1].(*WeatherLocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_Create_Call) Return(err error) *MockWeatherRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeatherRepository_Create_Call) RunAndReturn(run func(ctx context.Context, l *WeatherLocation) error) *MockWeatherRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeatherRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWeatherRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWeatherRepository_Expecter) Delete(ctx any, id any) *MockWeatherRepository_Delete_Call {
	return &MockWeatherRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWeatherRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWeatherRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_Delete_Call) Return(err error) *MockWeatherRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeatherRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockWeatherRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) Get(ctx context.Context, id uuid.UUID) (*WeatherLocation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *WeatherLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*WeatherLocation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *WeatherLocation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WeatherLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWeatherRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWeatherRepository_Expecter) Get(ctx any, id any) *MockWeatherRepository_Get_Call {
	return &MockWeatherRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockWeatherRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWeatherRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_Get_Call) Return(weatherLocation *WeatherLocation, err error) *MockWeatherRepository_Get_Call {
	_c.Call.Return(weatherLocation, err)
	return _c
}

func (_c *MockWeatherRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*WeatherLocation, error)) *MockWeatherRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]WeatherLocation, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []WeatherLocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]WeatherLocation, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []WeatherLocation); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WeatherLocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockWeatherRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWeatherRepository_Expecter) ListByUser(ctx any, userID any) *MockWeatherRepository_ListByUser_Call {
	return &MockWeatherRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockWeatherRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWeatherRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_ListByUser_Call) Return(weatherLocations []WeatherLocation, err error) *MockWeatherRepository_ListByUser_Call {
	_c.Call.Return(weatherLocations, err)
	return _c
}

func (_c *MockWeatherRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]WeatherLocation, error)) *MockWeatherRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) SetDefault(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeatherRepository_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockWeatherRepository_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockWeatherRepository_Expecter) SetDefault(ctx any, userID any, id any) *MockWeatherRepository_SetDefault_Call {
	return &MockWeatherRepository_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, userID, id)}
}

func (_c *MockWeatherRepository_SetDefault_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockWeatherRepository_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_SetDefault_Call) Return(err error) *MockWeatherRepository_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeatherRepository_SetDefault_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockWeatherRepository_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLabel provides a mock function for the type MockWeatherRepository
func (_mock *MockWeatherRepository) UpdateLabel(ctx context.Context, id uuid.UUID, label string) error {
	ret := _mock.Called(ctx, id, label)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, label)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWeatherRepository_UpdateLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLabel'
type MockWeatherRepository_UpdateLabel_Call struct {
	*mock.Call
}

// UpdateLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - label string
func (_e *MockWeatherRepository_Expecter) UpdateLabel(ctx any, id any, label any) *MockWeatherRepository_UpdateLabel_Call {
	return &MockWeatherRepository_UpdateLabel_Call{Call: _e.mock.On("UpdateLabel", ctx, id, label)}
}

func (_c *MockWeatherRepository_UpdateLabel_Call) Run(run func(ctx context.Context, id uuid.UUID, label string)) *MockWeatherRepository_UpdateLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWeatherRepository_UpdateLabel_Call) Return(err error) *MockWeatherRepository_UpdateLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWeatherRepository_UpdateLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, label string) error) *MockWeatherRepository_UpdateLabel_Call {
	_c.Call.Return(run)
	return _c
}
