// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package weather

import (
	"Sixth_world_Sunday/internal/dto"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, userID any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID uuid.UUID) (*dto.WeatherLocationListResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.WeatherLocationListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.WeatherLocationListResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.WeatherLocationListResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WeatherLocationListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) List(ctx any, userID any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(weatherLocationListResponse *dto.WeatherLocationListResponse, err error) *MockService_List_Call {
	_c.Call.Return(weatherLocationListResponse, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*dto.WeatherLocationListResponse, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockService
func (_mock *MockService) Rename(ctx context.Context, userID uuid.UUID, id uuid.UUID, label string) (*dto.WeatherLocationResponse, error) {
	ret := _mock.Called(ctx, userID, id, label)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 *dto.WeatherLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*dto.WeatherLocationResponse, error)); ok {
		return returnFunc(ctx, userID, id, label)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *dto.WeatherLocationResponse); ok {
		r0 = returnFunc(ctx, userID, id, label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WeatherLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, id, label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockService_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - label string
func (_e *MockService_Expecter) Rename(ctx any, userID any, id any, label any) *MockService_Rename_Call {
	return &MockService_Rename_Call{Call: _e.mock.On("Rename", ctx, userID, id, label)}
}

func (_c *MockService_Rename_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, label string)) *MockService_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Rename_Call) Return(weatherLocationResponse *dto.WeatherLocationResponse, err error) *MockService_Rename_Call {
	_c.Call.Return(weatherLocationResponse, err)
	return _c
}

func (_c *MockService_Rename_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, label string) (*dto.WeatherLocationResponse, error)) *MockService_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockService
func (_mock *MockService) Save(ctx context.Context, userID uuid.UUID, req dto.SaveWeatherLocationRequest) (*dto.WeatherLocationResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *dto.WeatherLocationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SaveWeatherLocationRequest) (*dto.WeatherLocationResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SaveWeatherLocationRequest) *dto.WeatherLocationResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WeatherLocationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.SaveWeatherLocationRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.SaveWeatherLocationRequest
func (_e *MockService_Expecter) Save(ctx any, userID any, req any) *MockService_Save_Call {
	return &MockService_Save_Call{Call: _e.mock.On("Save", ctx, userID, req)}
}

func (_c *MockService_Save_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.SaveWeatherLocationRequest)) *MockService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.SaveWeatherLocationRequest
		if args[2] != nil {
			arg2 = args[2].(dto.SaveWeatherLocationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Save_Call) Return(weatherLocationResponse *dto.WeatherLocationResponse, err error) *MockService_Save_Call {
	_c.Call.Return(weatherLocationResponse, err)
	return _c
}

func (_c *MockService_Save_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.SaveWeatherLocationRequest) (*dto.WeatherLocationResponse, error)) *MockService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type MockService
func (_mock *MockService) SetDefault(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockService_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) SetDefault(ctx any, userID any, id any) *MockService_SetDefault_Call {
	return &MockService_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, userID, id)}
}

func (_c *MockService_SetDefault_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetDefault_Call) Return(err error) *MockService_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetDefault_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}
