// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package maps

import (
	"Sixth_world_Sunday/internal/dto"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, userID uuid.UUID, req dto.SaveMapRequest) (*dto.MapResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.MapResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SaveMapRequest) (*dto.MapResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.SaveMapRequest) *dto.MapResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MapResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.SaveMapRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.SaveMapRequest
func (_e *MockService_Expecter) Create(ctx any, userID any, req any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.SaveMapRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.SaveMapRequest
		if args[2] != nil {
			arg2 = args[2].(dto.SaveMapRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(mapResponse *dto.MapResponse, err error) *MockService_Create_Call {
	_c.Call.Return(mapResponse, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.SaveMapRequest) (*dto.MapResponse, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, userID any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, viewerID uuid.UUID) (*dto.MapListResponse, error) {
	ret := _mock.Called(ctx, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.MapListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.MapListResponse, error)); ok {
		return returnFunc(ctx, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.MapListResponse); ok {
		r0 = returnFunc(ctx, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MapListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) List(ctx any, viewerID any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, viewerID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, viewerID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(mapListResponse *dto.MapListResponse, err error) *MockService_List_Call {
	_c.Call.Return(mapListResponse, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, viewerID uuid.UUID) (*dto.MapListResponse, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.SaveMapRequest) (*dto.MapResponse, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.MapResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SaveMapRequest) (*dto.MapResponse, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SaveMapRequest) *dto.MapResponse); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MapResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.SaveMapRequest) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - req dto.SaveMapRequest
func (_e *MockService_Expecter) Update(ctx any, userID any, id any, req any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.SaveMapRequest)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.SaveMapRequest
		if args[3] != nil {
			arg3 = args[3].(dto.SaveMapRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(mapResponse *dto.MapResponse, err error) *MockService_Update_Call {
	_c.Call.Return(mapResponse, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.SaveMapRequest) (*dto.MapResponse, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
