// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package event

import (
	"Sixth_world_Sunday/internal/dto"
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockService
func (_mock *MockService) Cancel(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) Cancel(ctx any, userID any, id any) *MockService_Cancel_Call {
	return &MockService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, userID, id)}
}

func (_c *MockService_Cancel_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Cancel_Call) Return(err error) *MockService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Cancel_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, userID uuid.UUID, req dto.CreateEventRequest) (*dto.EventResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.EventResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateEventRequest) (*dto.EventResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateEventRequest) *dto.EventResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EventResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateEventRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateEventRequest
func (_e *MockService_Expecter) Create(ctx any, userID any, req any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateEventRequest)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateEventRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateEventRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(eventResponse *dto.EventResponse, err error) *MockService_Create_Call {
	_c.Call.Return(eventResponse, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.CreateEventRequest) (*dto.EventResponse, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, userID any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, viewerID uuid.UUID) (*dto.EventListResponse, error) {
	ret := _mock.Called(ctx, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.EventListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.EventListResponse, error)); ok {
		return returnFunc(ctx, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.EventListResponse); ok {
		r0 = returnFunc(ctx, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EventListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) List(ctx any, viewerID any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, viewerID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, viewerID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(eventListResponse *dto.EventListResponse, err error) *MockService_List_Call {
	_c.Call.Return(eventListResponse, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, viewerID uuid.UUID) (*dto.EventListResponse, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetRSVP provides a mock function for the type MockService
func (_mock *MockService) SetRSVP(ctx context.Context, userID uuid.UUID, id uuid.UUID, interested bool) error {
	ret := _mock.Called(ctx, userID, id, interested)

	if len(ret) == 0 {
		panic("no return value specified for SetRSVP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, id, interested)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetRSVP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRSVP'
type MockService_SetRSVP_Call struct {
	*mock.Call
}

// SetRSVP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - interested bool
func (_e *MockService_Expecter) SetRSVP(ctx any, userID any, id any, interested any) *MockService_SetRSVP_Call {
	return &MockService_SetRSVP_Call{Call: _e.mock.On("SetRSVP", ctx, userID, id, interested)}
}

func (_c *MockService_SetRSVP_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, interested bool)) *MockService_SetRSVP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetRSVP_Call) Return(err error) *MockService_SetRSVP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetRSVP_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, interested bool) error) *MockService_SetRSVP_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.UpdateEventRequest) (*dto.EventResponse, error) {
	ret := _mock.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.EventResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateEventRequest) (*dto.EventResponse, error)); ok {
		return returnFunc(ctx, userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateEventRequest) *dto.EventResponse); ok {
		r0 = returnFunc(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EventResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateEventRequest) error); ok {
		r1 = returnFunc(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - req dto.UpdateEventRequest
func (_e *MockService_Expecter) Update(ctx any, userID any, id any, req any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, req)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.UpdateEventRequest)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateEventRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateEventRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(eventResponse *dto.EventResponse, err error) *MockService_Update_Call {
	_c.Call.Return(eventResponse, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, req dto.UpdateEventRequest) (*dto.EventResponse, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCover provides a mock function for the type MockService
func (_mock *MockService) UploadCover(ctx context.Context, userID uuid.UUID, size int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, userID, size, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadCover")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, userID, size, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, userID, size, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, userID, size, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCover'
type MockService_UploadCover_Call struct {
	*mock.Call
}

// UploadCover is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - size int64
//   - reader io.Reader
func (_e *MockService_Expecter) UploadCover(ctx any, userID any, size any, reader any) *MockService_UploadCover_Call {
	return &MockService_UploadCover_Call{Call: _e.mock.On("UploadCover", ctx, userID, size, reader)}
}

func (_c *MockService_UploadCover_Call) Run(run func(ctx context.Context, userID uuid.UUID, size int64, reader io.Reader)) *MockService_UploadCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UploadCover_Call) Return(s string, err error) *MockService_UploadCover_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_UploadCover_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, size int64, reader io.Reader) (string, error)) *MockService_UploadCover_Call {
	_c.Call.Return(run)
	return _c
}
