// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filehost

import (
	"Sixth_world_Sunday/internal/dto"
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Browse provides a mock function for the type MockService
func (_mock *MockService) Browse(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID) (*dto.VaultBrowseResponse, error) {
	ret := _mock.Called(ctx, userID, folderID)

	if len(ret) == 0 {
		panic("no return value specified for Browse")
	}

	var r0 *dto.VaultBrowseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (*dto.VaultBrowseResponse, error)); ok {
		return returnFunc(ctx, userID, folderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) *dto.VaultBrowseResponse); ok {
		r0 = returnFunc(ctx, userID, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VaultBrowseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, folderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Browse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browse'
type MockService_Browse_Call struct {
	*mock.Call
}

// Browse is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - folderID *uuid.UUID
func (_e *MockService_Expecter) Browse(ctx any, userID any, folderID any) *MockService_Browse_Call {
	return &MockService_Browse_Call{Call: _e.mock.On("Browse", ctx, userID, folderID)}
}

func (_c *MockService_Browse_Call) Run(run func(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID)) *MockService_Browse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Browse_Call) Return(vaultBrowseResponse *dto.VaultBrowseResponse, err error) *MockService_Browse_Call {
	_c.Call.Return(vaultBrowseResponse, err)
	return _c
}

func (_c *MockService_Browse_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID) (*dto.VaultBrowseResponse, error)) *MockService_Browse_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFolder provides a mock function for the type MockService
func (_mock *MockService) CreateFolder(ctx context.Context, userID uuid.UUID, name string, parentID *uuid.UUID) (*dto.VaultFolderResponse, error) {
	ret := _mock.Called(ctx, userID, name, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateFolder")
	}

	var r0 *dto.VaultFolderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID) (*dto.VaultFolderResponse, error)); ok {
		return returnFunc(ctx, userID, name, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID) *dto.VaultFolderResponse); ok {
		r0 = returnFunc(ctx, userID, name, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VaultFolderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, name, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFolder'
type MockService_CreateFolder_Call struct {
	*mock.Call
}

// CreateFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
//   - parentID *uuid.UUID
func (_e *MockService_Expecter) CreateFolder(ctx any, userID any, name any, parentID any) *MockService_CreateFolder_Call {
	return &MockService_CreateFolder_Call{Call: _e.mock.On("CreateFolder", ctx, userID, name, parentID)}
}

func (_c *MockService_CreateFolder_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string, parentID *uuid.UUID)) *MockService_CreateFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_CreateFolder_Call) Return(vaultFolderResponse *dto.VaultFolderResponse, err error) *MockService_CreateFolder_Call {
	_c.Call.Return(vaultFolderResponse, err)
	return _c
}

func (_c *MockService_CreateFolder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, name string, parentID *uuid.UUID) (*dto.VaultFolderResponse, error)) *MockService_CreateFolder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockService
func (_mock *MockService) DeleteFile(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteFile(ctx any, userID any, id any) *MockService_DeleteFile_Call {
	return &MockService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, userID, id)}
}

func (_c *MockService_DeleteFile_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteFile_Call) Return(err error) *MockService_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFolder provides a mock function for the type MockService
func (_mock *MockService) DeleteFolder(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type MockService_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteFolder(ctx any, userID any, id any) *MockService_DeleteFolder_Call {
	return &MockService_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, userID, id)}
}

func (_c *MockService_DeleteFolder_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteFolder_Call) Return(err error) *MockService_DeleteFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteFolder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// OpenForDownload provides a mock function for the type MockService
func (_mock *MockService) OpenForDownload(ctx context.Context, userID uuid.UUID, id uuid.UUID) (*DownloadInfo, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for OpenForDownload")
	}

	var r0 *DownloadInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*DownloadInfo, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *DownloadInfo); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DownloadInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_OpenForDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenForDownload'
type MockService_OpenForDownload_Call struct {
	*mock.Call
}

// OpenForDownload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) OpenForDownload(ctx any, userID any, id any) *MockService_OpenForDownload_Call {
	return &MockService_OpenForDownload_Call{Call: _e.mock.On("OpenForDownload", ctx, userID, id)}
}

func (_c *MockService_OpenForDownload_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_OpenForDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_OpenForDownload_Call) Return(downloadInfo *DownloadInfo, err error) *MockService_OpenForDownload_Call {
	_c.Call.Return(downloadInfo, err)
	return _c
}

func (_c *MockService_OpenForDownload_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) (*DownloadInfo, error)) *MockService_OpenForDownload_Call {
	_c.Call.Return(run)
	return _c
}

// RenameFile provides a mock function for the type MockService
func (_mock *MockService) RenameFile(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string) error {
	ret := _mock.Called(ctx, userID, id, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RenameFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameFile'
type MockService_RenameFile_Call struct {
	*mock.Call
}

// RenameFile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - name string
func (_e *MockService_Expecter) RenameFile(ctx any, userID any, id any, name any) *MockService_RenameFile_Call {
	return &MockService_RenameFile_Call{Call: _e.mock.On("RenameFile", ctx, userID, id, name)}
}

func (_c *MockService_RenameFile_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string)) *MockService_RenameFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RenameFile_Call) Return(err error) *MockService_RenameFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RenameFile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string) error) *MockService_RenameFile_Call {
	_c.Call.Return(run)
	return _c
}

// RenameFolder provides a mock function for the type MockService
func (_mock *MockService) RenameFolder(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string) error {
	ret := _mock.Called(ctx, userID, id, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameFolder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RenameFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameFolder'
type MockService_RenameFolder_Call struct {
	*mock.Call
}

// RenameFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - name string
func (_e *MockService_Expecter) RenameFolder(ctx any, userID any, id any, name any) *MockService_RenameFolder_Call {
	return &MockService_RenameFolder_Call{Call: _e.mock.On("RenameFolder", ctx, userID, id, name)}
}

func (_c *MockService_RenameFolder_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string)) *MockService_RenameFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RenameFolder_Call) Return(err error) *MockService_RenameFolder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RenameFolder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, name string) error) *MockService_RenameFolder_Call {
	_c.Call.Return(run)
	return _c
}

// SetFileLocked provides a mock function for the type MockService
func (_mock *MockService) SetFileLocked(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool) error {
	ret := _mock.Called(ctx, userID, id, locked)

	if len(ret) == 0 {
		panic("no return value specified for SetFileLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, id, locked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetFileLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFileLocked'
type MockService_SetFileLocked_Call struct {
	*mock.Call
}

// SetFileLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - locked bool
func (_e *MockService_Expecter) SetFileLocked(ctx any, userID any, id any, locked any) *MockService_SetFileLocked_Call {
	return &MockService_SetFileLocked_Call{Call: _e.mock.On("SetFileLocked", ctx, userID, id, locked)}
}

func (_c *MockService_SetFileLocked_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool)) *MockService_SetFileLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetFileLocked_Call) Return(err error) *MockService_SetFileLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetFileLocked_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool) error) *MockService_SetFileLocked_Call {
	_c.Call.Return(run)
	return _c
}

// SetFolderLocked provides a mock function for the type MockService
func (_mock *MockService) SetFolderLocked(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool) error {
	ret := _mock.Called(ctx, userID, id, locked)

	if len(ret) == 0 {
		panic("no return value specified for SetFolderLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, id, locked)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetFolderLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFolderLocked'
type MockService_SetFolderLocked_Call struct {
	*mock.Call
}

// SetFolderLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - locked bool
func (_e *MockService_Expecter) SetFolderLocked(ctx any, userID any, id any, locked any) *MockService_SetFolderLocked_Call {
	return &MockService_SetFolderLocked_Call{Call: _e.mock.On("SetFolderLocked", ctx, userID, id, locked)}
}

func (_c *MockService_SetFolderLocked_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool)) *MockService_SetFolderLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetFolderLocked_Call) Return(err error) *MockService_SetFolderLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetFolderLocked_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, locked bool) error) *MockService_SetFolderLocked_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockService
func (_mock *MockService) Upload(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID, originalName string, size int64, reader io.Reader) (*dto.VaultFileResponse, error) {
	ret := _mock.Called(ctx, userID, folderID, originalName, size, reader)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *dto.VaultFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, string, int64, io.Reader) (*dto.VaultFileResponse, error)); ok {
		return returnFunc(ctx, userID, folderID, originalName, size, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, string, int64, io.Reader) *dto.VaultFileResponse); ok {
		r0 = returnFunc(ctx, userID, folderID, originalName, size, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VaultFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, string, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, userID, folderID, originalName, size, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - folderID *uuid.UUID
//   - originalName string
//   - size int64
//   - reader io.Reader
func (_e *MockService_Expecter) Upload(ctx any, userID any, folderID any, originalName any, size any, reader any) *MockService_Upload_Call {
	return &MockService_Upload_Call{Call: _e.mock.On("Upload", ctx, userID, folderID, originalName, size, reader)}
}

func (_c *MockService_Upload_Call) Run(run func(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID, originalName string, size int64, reader io.Reader)) *MockService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_Upload_Call) Return(vaultFileResponse *dto.VaultFileResponse, err error) *MockService_Upload_Call {
	_c.Call.Return(vaultFileResponse, err)
	return _c
}

func (_c *MockService_Upload_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, folderID *uuid.UUID, originalName string, size int64, reader io.Reader) (*dto.VaultFileResponse, error)) *MockService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
